// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwh3oCYECkoaaNhSMdLUCVr5f3Up6rYhY',
    appId: '1:533838227281:web:2d4245ad1bc2d06c119570',
    messagingSenderId: '533838227281',
    projectId: 'flutter-api-yungshop',
    authDomain: 'flutter-api-yungshop.firebaseapp.com',
    storageBucket: 'flutter-api-yungshop.appspot.com',
    measurementId: 'G-HW006EEQ7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZrwbUterr4EeGL86azZip2wd-QicP8ZI',
    appId: '1:533838227281:android:ded7cfa317876c82119570',
    messagingSenderId: '533838227281',
    projectId: 'flutter-api-yungshop',
    storageBucket: 'flutter-api-yungshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWQCWgC1V0eT-jMOkctcvgHgpywTHX0iY',
    appId: '1:533838227281:ios:06d40b25cbd0097e119570',
    messagingSenderId: '533838227281',
    projectId: 'flutter-api-yungshop',
    storageBucket: 'flutter-api-yungshop.appspot.com',
    iosBundleId: 'com.example.nguyenManhDung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWQCWgC1V0eT-jMOkctcvgHgpywTHX0iY',
    appId: '1:533838227281:ios:0cec14574acde1c0119570',
    messagingSenderId: '533838227281',
    projectId: 'flutter-api-yungshop',
    storageBucket: 'flutter-api-yungshop.appspot.com',
    iosBundleId: 'com.example.nguyenManhDung.RunnerTests',
  );
}
